// <auto-generated />
namespace biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class estadoclientes_delete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estadoclientes_delete));
        
        string IMigrationMetadata.Id
        {
            get { return "202110262352261_estadoclientes_delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
