// <auto-generated />
namespace biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fecha_pub_libro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fecha_pub_libro));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261627016_fecha_pub_libro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
